/**
 * An apex page controller that takes the user to the right start page based on credentials or lack thereof
 */
@isTest public with sharing class CommunitiesSelfRegConfirmControllerTest {
    @isTest public static void testCommunitiesSelfRegConfirmController() { //NOPMD
        // Instantiate a new controller with all parameters in the page
        CommunitiesSelfRegConfirmController controller = new CommunitiesSelfRegConfirmController(); // NOPMD
      }    
}