/**
 * @description Interface for Breach DAO framework
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                             |
 *    |--------------------------------|-----------------------|------------------------|--------------------------------------------|
 *    | arsenio.jr.dayrit              | May 9, 2024           | DEPP-8487              | created file                               |
 */
public interface IBreachesDAO extends DmlInterface{ 
    
} 