/**
 * @description Interface for Engagement List Configuration DAO
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.munoz                 | May 16, 2024          | DEPP-8484              | Created file
 */
public interface IEngagementListConfigurationsDAO extends DmlInterface{
  
}