/**
 * @description Interface for Financial Summary DAO
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | July 12, 2023         | DEPP-5473              | Created file
 */
public interface IFinanceSummariesDAO extends DmlInterface {
}
