/**
 * @description Interface for Milestone DAO
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | July 5, 2023          | DEPP-5474             | Created file
 */
public interface IMilestonesDAO extends DmlInterface {
}
