/**
 * @description Interface for Relationship Managers DAO
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eugene.andrew.abuan            | August 01, 2023       | DEPP-6140              | Created file                 |
 */
public interface IRelationshipManagersDAO extends DmlInterface {
}
