/**
 * @description Interface for Service Appointment DAO framework
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                             |
      |--------------------------------|-----------------------|------------------------|--------------------------------------------|
      | arsenio.jr.dayrit              | November 22, 2023     | DEPP-7264              | Created File                               |
      
 */
public interface IServiceAppointmentsDAO extends DmlInterface{ 

} 