/**
 * @description Interface for Stewardship DAO
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | nicole.genon                   | March 6, 2024         | DEPP-7922              | Created file
 */
public interface IStewardshipsDAO  extends DmlInterface {
    //List<List_Contributor__c> getListContributorByListID(Set<Id> listID, AccessLevel accessLevel);
}