/**
 * @description Test class that contains reusable method for test data creation
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA                | Change Summary                           |
 *    |---------------------------|-----------------------|---------------------|------------------------------------------|
 *    | julie.jane.alegre         | April 16, 2024        | DEPP-8016           | Created file                             |
 **/

 @isTest
 public with sharing class TestDataFactoryUserTest {
    @testSetup
    static void testSetup() {
        
    }

}
