name: "IT1FebCI Deploy (Triggered on creation of PR)"

resources:
  repositories:
    - repository: SFDX-PIPELINES
      type: bitbucket
      endpoint: Bitbucket_QUT
      name: qutdev/sfdx-pipelines
      ref: main ## PRODUCTION pipeline branch
      #ref: feature/DEPP-790 ## DEV pipeline branch
      trigger: none

# Build pull requests so we can test them
pr:
  autoCancel: true
  drafts: false
  branches:
    include:
      - release/IT1Feb

#Custom Variables
variables:
  - group: SF_CICD

stages:
  - stage: PiplineJob
    displayName: "Validate"
    lockBehavior: runLatest
    jobs:
      - deployment: ValidateIT1Feb
        timeoutInMinutes: 600
        pool:
          vmImage: "ubuntu-latest"
        container: adammbest/sfdx:latest
        environment: "IT1FebCI"
        variables:
          - group: IT1FebCI
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: SFDX-PIPELINES
                - checkout: self
                - task: DownloadSecureFile@1
                  name: jwtKeyfile
                  inputs:
                    secureFile: "server.key"
                - template: yml/templates/sfdx-init.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-login.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-build-package.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-scan-code.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-pre-deploy-steps.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-deploy-and-post-deploy.yml@SFDX-PIPELINES
                  parameters:
                    validateOrDeploy: "Deploy"
                - template: yml/templates/sfdx-logout.yml@SFDX-PIPELINES
