name: "IT1FebCI Deploy (Triggered on creation of PR)"

resources:
  repositories:
    - repository: SFDX-PIPELINES
      type: bitbucket
      endpoint: Bitbucket_QUT
      name: qutdev/sfdx-pipelines
      ref: main ## PRODUCTION pipeline branch
      #ref: feature/DEPP-2855-navmenufix ## DEV pipeline branch
      trigger: none

# Build pull requests so we can test them
pr:
  autoCancel: true
  drafts: false
  branches:
    include:
      - release/IT1Feb

#Custom Variables
variables:
  - group: SF_CICD

parameters:
- name: INCLUDE_SANDBOX_REFRESH_STEP_LoadUsers
  displayName: Include Add/Update Test Users
  type: string
  default: "Yes"
  values:
  - "Yes"
  - "No"

- name: PACKAGE_DEPLOYMENT_DELTA_TYPE
  displayName: Package Deployment Delta Type
  type: string
  default: "Diff from target branch"
  values:
  - "Diff from main"
  - "Diff from target branch"
  - "Last 5 days"
  - "Last 10 days"

- name: TARGET_BRANCH
  displayName: Target Branch
  type: string
  default: release/IT1Feb

stages:
  - stage: PiplineJob
    displayName: "Validate"
    lockBehavior: runLatest
    jobs:
      - deployment: ValidateIT1Feb
        timeoutInMinutes: 600
        pool:
          vmImage: "ubuntu-latest"
        container: adammbest/sfdx:latest
        environment: "IT1FebCI"
        variables:
          - group: IT1FebCI
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: SFDX-PIPELINES
                - checkout: self
                - task: DownloadSecureFile@1
                  name: jwtKeyfile
                  inputs:
                    secureFile: "server.key"
                - template: yml/templates/sfdx-init.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-login.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-build-package.yml@SFDX-PIPELINES
                  parameters:
                    PACKAGE_DEPLOYMENT_DELTA_TYPE: "${{ parameters.PACKAGE_DEPLOYMENT_DELTA_TYPE }}"
                    TARGET_BRANCH: "${{ parameters.TARGET_BRANCH }}"
                - template: yml/templates/sfdx-scan-code.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-pre-deploy-steps.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-deploy-and-post-deploy.yml@SFDX-PIPELINES
                  parameters:
                    validateOrDeploy: "Deploy"
                - template: yml/templates/sfdx-deploy-test-users.yml@SFDX-PIPELINES
                  parameters:
                    INCLUDE_SANDBOX_REFRESH_STEP_LoadUsers: "${{ parameters.INCLUDE_SANDBOX_REFRESH_STEP_LoadUsers }}"
                - template: yml/templates/sfdx-logout.yml@SFDX-PIPELINES
