name: "SIT Deploy (7am AEST)"

resources:
  repositories:
    - repository: SFDX-PIPELINES
      type: bitbucket
      endpoint: Bitbucket_QUT
      name: qutdev/sfdx-pipelines
      ref: main ## PRODUCTION pipeline branch (to merge and put live when bitbucket pipeline is fully off)
      #ref: feature/DEPP-3279-deleteflowinterviews ## DEV pipeline branch

# Deploy to branch on commit
trigger: none

schedules:
  - cron: 0 21 * * * #At 07:00 every day brisbane (AEST) time.  https://crontab.guru/#0_7_*_*_*
    displayName: Deployment to SIT (7am weekdays)
    always: true
    branches:
      include:
        - develop

#Custom Variables
variables:
  - group: SF_CICD

parameters:
- name: PACKAGE_DEPLOYMENT_DELTA_TYPE
  displayName: Package Deployment Delta Type
  type: string
  default: "Diff from main"
  values:
  - "Diff from main"
  - "Last 5 days"
  - "Last 10 days"
  - "Full Deployment"
  
- name: INCLUDE_SANDBOX_REFRESH_STEP_LoadUsers
  displayName: Include Add/Update Test Users
  type: string
  default: "Yes"
  values:
  - "Yes"
  - "No"

stages:
  - stage: PiplineJob
    displayName: "Deploy"
    lockBehavior: runLatest
    jobs:
      - deployment: Deploy
        timeoutInMinutes: 600
        pool:
          vmImage: "ubuntu-latest"
        container: adammbest/sfdx:1.2
        environment: "SIT"
        variables:
          - group: SIT
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: SFDX-PIPELINES
                - checkout: self
                - task: DownloadSecureFile@1
                  name: jwtKeyfile
                  inputs:
                    secureFile: "server.key"
                - template: yml/templates/sfdx-init.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-login.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-build-package.yml@SFDX-PIPELINES
                  parameters:
                    PACKAGE_DEPLOYMENT_DELTA_TYPE: "${{ parameters.PACKAGE_DEPLOYMENT_DELTA_TYPE }}"
                - template: yml/templates/sfdx-scan-code.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-pre-deploy-steps.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-deploy-and-post-deploy.yml@SFDX-PIPELINES
                  parameters:
                    validateOrDeploy: "Deploy"
                - template: yml/templates/sfdx-deploy-test-users.yml@SFDX-PIPELINES
                  parameters:
                    INCLUDE_SANDBOX_REFRESH_STEP_LoadUsers: "${{ parameters.INCLUDE_SANDBOX_REFRESH_STEP_LoadUsers }}"
                - template: yml/templates/sfdx-logout.yml@SFDX-PIPELINES
