name: "UAT Deploy"

resources:
  repositories:
    - repository: SFDX-PIPELINES
      type: bitbucket
      endpoint: Bitbucket_QUT
      name: qutdev/sfdx-pipelines
      ref: main ## PRODUCTION pipeline branch (to merge and put live when bitbucket pipeline is fully off)
      #ref: feature/DEPP-790 ## DEV pipeline branch

#Custom Variables
variables:
  - group: SF_CICD

parameters:
- name: PACKAGE_DEPLOYMENT_DELTA_TYPE
  displayName: Package Deployment Delta Type
  type: string
  default: "Diff from main"
  values:
  - "Diff from main"
  - "Last 5 days"
  - "Last 10 days"
  - "Full Deployment"
  
stages:
  - stage: PiplineJob
    displayName: "Deploy"
    lockBehavior: runLatest
    jobs:
      - deployment: Deploy
        timeoutInMinutes: 600
        pool:
          vmImage: "ubuntu-latest"
        container: adammbest/sfdx:1.2
        environment: "UAT"
        variables:
          - group: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: SFDX-PIPELINES
                - checkout: self
                - task: DownloadSecureFile@1
                  name: jwtKeyfile
                  inputs:
                    secureFile: "server.key"
                - template: yml/templates/sfdx-init.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-login.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-build-package.yml@SFDX-PIPELINES
                  parameters:
                    PACKAGE_DEPLOYMENT_DELTA_TYPE: "${{ parameters.PACKAGE_DEPLOYMENT_DELTA_TYPE }}"
                - template: yml/templates/sfdx-scan-code.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-pre-deploy-steps.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-deploy-and-post-deploy.yml@SFDX-PIPELINES
                  parameters:
                    validateOrDeploy: "Deploy"
                - template: yml/templates/sfdx-logout.yml@SFDX-PIPELINES
