name: "UATST Deploy (Triggered on creation of UAT PR)"

resources:
  repositories:
    - repository: SFDX-PIPELINES
      type: bitbucket
      endpoint: Bitbucket_QUT
      name: qutdev/sfdx-pipelines
      ref: main ## PRODUCTION pipeline branch
      #ref: feature/DEPP-2855-navmenufix ## DEV pipeline branch sdf
      trigger: none


# Build pull requests so we can test them
pr:
  autoCancel: true
  drafts: false
  branches:
    include:
      - $(BRANCH_LISTENED)

#Custom Variables
variables:
  - group: SF_CICD

parameters:
- name: PACKAGE_DEPLOYMENT_DELTA_TYPE
  displayName: Package Deployment Delta Type
  type: string
  default: "Diff from target branch"
  values:
  - "Diff from main"
  - "Diff from target branch"
  - "Last 5 days"
  - "Last 10 days"
  - "Full Deployment"

- name: TARGET_BRANCH
  displayName: Target Branch
  type: string
  default: uat

stages:
  - stage: PiplineJob
    displayName: "Validate"
    lockBehavior: runLatest
    jobs:
      - deployment: Validate
        timeoutInMinutes: 600
        pool:
          vmImage: "ubuntu-latest"
        container: qutinohmonton/inohsfdx:test
        environment: "UATST"
        variables:
          - group: UATST
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: SFDX-PIPELINES
                - checkout: self
                - task: DownloadSecureFile@1
                  name: jwtKeyfile
                  inputs:
                    secureFile: "server.key"
                - template: yml/templates/sfdx-init.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-login.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-build-package.yml@SFDX-PIPELINES
                  parameters:
                    PACKAGE_DEPLOYMENT_DELTA_TYPE: "${{ parameters.PACKAGE_DEPLOYMENT_DELTA_TYPE }}"
                    TARGET_BRANCH: "${{ parameters.TARGET_BRANCH }}"
                - template: yml/templates/sfdx-scan-code.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-pre-deploy-steps.yml@SFDX-PIPELINES
                - template: yml/templates/check-build-queue.yml@SFDX-PIPELINES
                - template: yml/templates/sfdx-deploy-and-post-deploy.yml@SFDX-PIPELINES
                  parameters:
                    validateOrDeploy: "Deploy"
                - template: yml/templates/sfdx-logout.yml@SFDX-PIPELINES
