# ██████████   █████ █████  █████████   █████████                     ████
#░░███░░░░███ ░░███ ░░███  ███░░░░░░   ███░░░░░███                   ░░███
#  ███   ░░███ ░░███ ███  ░███ ██████ ░███    ░░░   ██████   ██████   ░███   ██████
# ░███    ░███  ░░█████   ░███░███░███░░█████████  ███░░███ ░░░░░███  ░███  ███░░███
# ░███    ░███   ███░███  ░███░███░███ ░░░░░░░░███░███ ░░░   ███████  ░███ ░███████
# ░███    ███   ███ ░░███ ░███░░░ ░███ ███    ░███░███  ███ ███░░███  ░███ ░███░░░
# ██████████   █████ █████░░█████████ ░░█████████ ░░██████ ░░████████ █████░░██████
# ░░░░░░░░░░   ░░░░░ ░░░░░  ░░░░░░░░░   ░░░░░░░░░   ░░░░░░   ░░░░░░░░ ░░░░░  ░░░░░░
# 
# DX@Scale CI/CD Template for Azure Pipelines
#-----------------------------------------------------------------------------------------------------------
# Maintained by @ramesh-karanji(Ramesh Karanji)
# Follows reference pipeline available at docs.dxatscale.io
# 
#------------------------------------------------------------------------------------------------------------
# To know more about dxatscale, visit https://docs.dxatscale.io
# To know more on sfpowerscripts, visit- https://sfpowerscripts.dxatscale.io/
# To know more on sfpowerkit, visit- https://github.com/Accenture/sfpowerkit

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is opened with 
# one of the specified target branches, or when updates are made to such a pull request.
#
# This template will be triggered whenever a Pull request is raised against the main branch...
#
#
#
# --- To report metrics about the pipeline to datadog or newrelic, set these variables in CICD group
#
#  #SFPOWERSCRIPTS_NEWRELIC: 'true'
#  #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '<NEWRELIC_INSIGHT_INSERT_KEYS>'
# 
#  or if you are using Datadog
#  #SFPOWERSCRIPTS_DATADOG: 'true'
#  #SFPOWERSCRIPTS_DATADOG_HOST: '<DATADOG-HOST>'
#  #SFPOWERSCRIPTS_DATADOG_API_KEY: '<DATADOG-API-KEY>'
#
# or if you are using a Hosted StatsD server
#  
#  # SFPOWERSCRIPTS_STATSD: 'true'
#  # SFPOWERSCRIPTS_STATSD_HOST: '<STATSD_HOST_IP>'
#
# --------------------------------------------------------------------------------------------------------


name: 'PR Validation - Auto Triggered'

# Build pushes to main so we can release merged changes
trigger: none

# Build pull requests so we can test them
pr:
    autoCancel: true
    drafts: false
    branches:
        include:
            - release/IT1Sep

#Custom Variables
variables:
  - group: SF_CICD

#Stages to run as part Validate
stages:
    - stage: ValidatePMD

      displayName: ValidatePMD
      dependsOn: []
      jobs:
          - job: ValidatePMD
            displayName: 'Validate PMD'                     
            pool:
                vmImage: 'ubuntu-latest'           
            container: dxatscale/sfpowerscripts:latest         

            steps:

            - checkout: self
              persistCredentials: true
  
            - script: |
                  sfdx sfpowerscripts:analyze:pmd -b  -o pmd-output --format=csv 
              continueOnError: true
              displayName: 'PMD Validation'  


            - task: PublishBuildArtifacts@1
              inputs:
                    pathToPublish: pmd-output
                    artifactName: PMDResults


    - stage: ValidateSource
      lockBehavior: sequential
      variables:
       - group: IT1SepCI
      displayName: 'Validate Source'
      dependsOn: []
      jobs:
          - job: ValidateSource
            displayName: 'Validate Source'
               
            pool:
                vmImage: 'ubuntu-latest'
            container: dxatscale/sfpowerscripts:latest     

            steps:

            - checkout: self
              persistCredentials: true
            
            - task: DownloadSecureFile@1
              name: certificate
              inputs:
                secureFile: 'server.key'
            
            - script: |
                    sfdx force:auth:jwt:grant -f $(certificate.secureFilePath) -i $(CONSUMER_KEY) -r $(TEST_LOGIN_URL) -u $(USERNAME).$(SANDBOX_NAME) -a $(SANDBOX_NAME)
              displayName: 'Authenticate CI Sandbox'


            - script: |
                    sfdx sfpowerscripts:orchestrator:validateAgainstOrg -u $(SANDBOX_NAME) --coveragepercent=85
              displayName: 'Validate Source'
